AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for creating security groups

Resources:
  LambdaSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group allowing TCP port 80 from Lambda to ECS
      VpcId: !ImportValue VPCId

  ECSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group allowing TCP port 80 from ECS to EC2
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !GetAtt LambdaSG.GroupId

  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group allowing TCP port 80 from EC2 to ECS
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !GetAtt LambdaSG.GroupId
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !GetAtt ECSSG.GroupId
